# Generated by Django 4.2.16 on 2026-09-27 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('Web App', 'Web App'), ('AI Trust Firewall', 'AI Trust Firewall'), ('Protocol Safety Shield', 'Protocol Safety Shield'), ('Desktop Trust Guard', 'Desktop Trust Guard'), ('Data Layer', 'Data Layer')], max_length=64)),
                ('component', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], max_length=16)),
                ('cvss', models.DecimalField(decimal_places=1, max_digits=3)),
                ('mission_risk', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=16)),
                ('owner', models.CharField(max_length=64)),
                ('poc_steps', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IPCCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=16)),
                ('origin_policy', models.CharField(choices=[('Strict', 'Strict'), ('Allowlist', 'Allowlist'), ('None', 'None')], max_length=16)),
                ('param_validation', models.CharField(default='Pass', max_length=8)),
                ('status', models.CharField(choices=[('Allowed', 'Allowed'), ('Blocked', 'Blocked'), ('Under Review', 'Under Review')], default='Allowed', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuarantineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarantine_id', models.CharField(max_length=32, unique=True)),
                ('source', models.CharField(max_length=128)),
                ('threat_type', models.CharField(max_length=128)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=16)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('critical', 'critical')], default='info', max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofOfFixCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=32, unique=True)),
                ('patch_reference', models.CharField(max_length=64)),
                ('test_result', models.CharField(default='Passed', max_length=16)),
                ('evidence_hash', models.CharField(max_length=80)),
                ('signed_by', models.CharField(default='Sentinel Trinity Assessment Engine', max_length=128)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.finding')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=32, unique=True)),
                ('evidence_type', models.CharField(choices=[('Screenshot', 'Screenshot'), ('HTTP Request/Response', 'HTTP Request/Response'), ('Code Reference', 'Code Reference'), ('Log File', 'Log File'), ('Screen Recording', 'Screen Recording'), ('Test Payload', 'Test Payload'), ('Analyst Note', 'Analyst Note')], max_length=32)),
                ('captured_by', models.CharField(max_length=64)),
                ('sha256', models.CharField(max_length=80)),
                ('redacted', models.BooleanField(default=False)),
                ('content_preview', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='core.finding')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
